# Generated by Django 5.2.7 on 2025-10-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_embarcacao_dono_embarcacao_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPassageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('passagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.passagem')),
            ],
        ),
    ]
