# Generated by Django 5.2.7 on 2025-10-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_infopassageiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacao',
            name='tipo',
            field=models.CharField(default='Outro', max_length=50),
        ),
    ]
